version: '2'
services:
  web:
       build:
               context: ./php/online-shopping-system
               dockerfile: Dockerfile
       container_name: php_app
       
       depends_on: 
         - db  
       ports:
         - 8008:80
       volumes:
            - ./php/online-shopping-system:/var/www/html/
  db:
          container_name: mysqli2
          image: mysql:latest
          command: --default-authentication-plugin=mysql_native_password
          restart: always  
          volumes:
             - ./php/online-shopping-system/database/onlineshop.sql:/docker-entrypoint-initdb.d/onlineshop.sql
          environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: database
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
          ports:
           - 6033:3306
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin 
volumes:
    persistent:
# becarefull from hidden containers processus 
# do a docker ps -a to check exited container and delete  them f they exist
# mysql usually take a few time to load 
